services:
  postgres:
    image: postgres:alpine
    container_name: wizpilot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bizpilot
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
